# link about Paramter
#https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
Parameters:
  AvailabilityZone:
    Description: Give name of az where you want to deploy your instance
    Type: String
    Default: us-east-1a
  InstanceType:
    Description: WebServer EC2 instance type (has default, AllowedValues)
    Type: String
    Default: t2.micro
    AllowedValues:
      - t1.micro
      - t2.nano
      - t2.micro
      - t2.small
  KeyName:
    Description: Keyname which you want to use for SSH
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

#Link about Ec2 instance 
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0cff7528ff583bf9a"
      AvailabilityZone: !Ref AvailabilityZone
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName